### PR TITLE
fix: fall back to async_get_device when async_get_device_by_identifier is missing

### LINKED ISSUE #307: AttributeError: 'DeviceRegistry' object has no attribute 'async_get_device_by_identifier' — crashes setup in v2026.9.9r2
## Description

After updating to v2026.9.9r2 (via HACS) and restarting Home Assistant, the `frank_energie` config entry fails to set up entirely with an `AttributeError`. No entities are created — the integration is completely broken until reverted or patched.

## Steps to reproduce

1. Have frank_energie installed via HACS on a previous working version (v2026.8.8 in my case)
2. Update to v2026.9.9r2 via HACS
3. Restart Home Assistant
4. Check the log

## Expected behavior

The integration sets up normally and price/battery/charger entities are created.

## Actual behavior

ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <name> for frank_energie
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frank_energie/init.py", line 94, in async_setup_entry
    return await component.setup()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frank_energie/init.py", line 231, in setup
    if device := device_registry.async_get_device_by_identifier(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DeviceRegistry' object has no attribute 'async_get_device_by_identifier'

## Root cause

In `custom_components/frank_energie/__init__.py`, `setup()` runs this cleanup block for a legacy "Battery Sessions" umbrella device before creating the API/coordinators:

```python
device_registry = dr.async_get(self.hass)
if device := device_registry.async_get_device_by_identifier(
    (DOMAIN, f"{self.entry.entry_id}_{SERVICE_NAME_BATTERY_SESSIONS}"),
    config_entry_id=self.entry.entry_id,
):
    device_registry.async_remove_device(device.id)
    _LOGGER.debug("Removed obsolete Battery Sessions umbrella device")

async_get_device_by_identifier is not a method on Home Assistant Core's DeviceRegistry class — this looks like it was introduced in the same refactor that closed #279 (device_registry.async_get_device is deprecated), possibly mixing up the module-level helper with the instance method, or a method name that never existed in Core. This appears to still be present on main as of 2026-09-14.

Suggested fix

Replace the call with the actual Core API, e.g.:

device_registry = dr.async_get(self.hass)
if device := device_registry.async_get_device(
    identifiers={(DOMAIN, f"{self.entry.entry_id}_{SERVICE_NAME_BATTERY_SESSIONS}")}
):
    device_registry.async_remove_device(device.id)
    _LOGGER.debug("Removed obsolete Battery Sessions umbrella device")

(Please double check the exact signature against the HA Core version you're targeting — async_get_device takes identifiers/connections as sets of tuples, no config_entry_id kwarg.)

Workaround

As a local workaround, I removed the entire cleanup block (comment + code) from __init__.py. Since device isn't referenced anywhere else in setup(), this is safe short-term but obviously needs a proper upstream fix, since any HACS update overwrites the local patch.

Environment

- frank_energie version: v2026.9.9r2
- Home Assistant Core: 2026.7.2
- Frontend: 20260624.5
- Installation method: Home Assistant Container

### PR DESCRIPTION
**Pull request by Veldkornet**
## Problem

Setup crashed with `AttributeError: 'DeviceRegistry' object has no attribute 'async_get_device_by_identifier'` on some HA Core versions, leaving no entities created.

## Root cause

`async_get_device_by_identifier` is the current, config-entry-scoped device registry lookup — but it doesn't exist on older HA Core versions still within this integration's declared minimum support range (`hacs.json`: 2026.1.0). The obsolete "Battery Sessions" umbrella-device cleanup in `setup()` called it unconditionally.

(Worth noting: the reverse fix — falling back to `async_get_device` unconditionally — isn't right either. That method is deprecated for the same reason and is slated for removal in HA 2027.8.0.)

## Fix

Prefer `async_get_device_by_identifier` when available, and fall back to the deprecated `async_get_device` only on older Core that lacks it. The capability check is computed once at import time, matching the existing `_LIB_HAS_QUARTER_HOUR_PRICES` pattern already used in `sensor.py`.

## Testing

- Two new regression tests against the real HA device registry (`pytest-homeassistant-custom-component`'s real `hass` fixture) — one exercising each branch.
- Verified the root cause and the fix against real, unmodified Home Assistant Core (not simulated) using this repo's Docker dev environment:
  - HA Core 2026.1.0 (this integration's declared minimum): confirmed `async_get_device_by_identifier` genuinely doesn't exist.
  - HA Core 2026.9.2 (`latest`): confirmed clean setup with no errors, and confirmed the obsolete device is actually removed from the on-disk device registry after being injected.
- Full test suite passes; ruff clean.

Fixes #307

## Samenvatting door Sourcery

Maak het opschonen van verouderde Battery Sessions-apparaten compatibel met zowel de huidige als oudere ondersteunde versies van Home Assistant Core.

Bugfixes:
- Voorkom installatiefouten in oudere versies van Home Assistant Core door terug te vallen op de oude apparaatzoekmethode wanneer de nieuwere, aan configuratie-items gekoppelde zoekmethode niet beschikbaar is.
- Blijf verouderde overkoepelende Battery Sessions-apparaten verwijderen in alle ondersteunde versies van Home Assistant Core.

Tests:
- Voeg regressiedekking toe voor het opschonen van verouderde apparaten met behulp van zowel de huidige als oudere API's van het Home Assistant-apparaatregister.

<details>
<summary>Original summary in English</summary>

## Samenvatting door Sourcery

Maak het opschonen van verouderde Battery Sessions-apparaten compatibel met zowel de huidige als oudere ondersteunde versies van Home Assistant Core.

Bugfixes:
- Voorkom installatiefouten op oudere ondersteunde versies van Home Assistant Core door terug te vallen op het verouderde apparaatopzoekmechanisme wanneer de nieuwere API niet beschikbaar is.
- Blijf verouderde overkoepelende Battery Sessions-apparaten verwijderen in alle ondersteunde versies van Home Assistant Core.

Tests:
- Voeg regressiedekking toe voor zowel de voorkeursroute als de terugvalroute voor het opzoeken in het apparatenregister.

<details>
<summary>Original summary in English</summary>

## Samenvatting door Sourcery

Maak het opschonen van verouderde Battery Sessions-apparaten compatibel met zowel de huidige als oudere ondersteunde versies van Home Assistant Core.

Bugfixes:
- Voorkom installatiefouten op oudere ondersteunde versies van Home Assistant Core door terug te vallen op het legacy-apparaatregister wanneer de nieuwere zoek-API niet beschikbaar is.
- Blijf verouderde overkoepelende Battery Sessions-apparaten verwijderen in alle ondersteunde versies van Home Assistant Core.

Tests:
- Voeg regressiedekking toe voor zowel het moderne zoekpad voor apparaten als het terugvalpad voor oudere Core-versies.

<details>
<summary>Original summary in English</summary>

## Samenvatting door Sourcery

Maak het opruimen van verouderde Battery Sessions-apparaten compatibel met zowel de huidige als oudere ondersteunde versies van Home Assistant Core.

Bugfixes:
- Voorkom installatiefouten op oudere ondersteunde versies van Home Assistant Core door terug te vallen op het zoeken in het verouderde apparaatregister wanneer de nieuwere API niet beschikbaar is.
- Ga door met het verwijderen van verouderde overkoepelende Battery Sessions-apparaten in alle ondersteunde versies van Home Assistant Core.

Tests:
- Voeg regressiedekking toe voor zowel het moderne zoeken naar apparaten als het terugvalpad voor oudere Core-versies.

<details>
<summary>Original summary in English</summary>

## Samenvatting door Sourcery

Maak het opschonen van verouderde Battery Sessions-apparaten compatibel met zowel nieuwere als oudere ondersteunde versies van Home Assistant Core.

Bugfixes:
- Voorkom installatiefouten in oudere ondersteunde versies van Home Assistant Core door terug te vallen op het verouderde zoeken in het apparatenregister wanneer de nieuwere API met configuratie-entry-scoping niet beschikbaar is.
- Ga door met het verwijderen van verouderde overkoepelende Battery Sessions-apparaten in alle ondersteunde versies van Home Assistant Core.

Tests:
- Voeg regressiedekking toe voor zowel het voorkeurs- als het verouderde zoekpad voor apparaten, met gebruik van het echte apparatenregister van Home Assistant.

<details>
<summary>Original summary in English</summary>

## Samenvatting door Sourcery

Maak het opschonen van verouderde Battery Sessions-apparaten compatibel met zowel de huidige als oudere ondersteunde versies van Home Assistant Core.

Bugfixes:
- Voorkom installatiefouten op oudere ondersteunde versies van Home Assistant Core door terug te vallen op de verouderde zoekmethode voor het apparatenregister wanneer de configuratie-entry-specifieke zoekmethode niet beschikbaar is.
- Ga door met het verwijderen van verouderde overkoepelende Battery Sessions-apparaten op alle ondersteunde versies van Home Assistant Core.

Tests:
- Voeg regressiedekking toe voor zowel de voorkeursroute als de verouderde route voor het zoeken in het apparatenregister, met behulp van het echte apparatenregister van Home Assistant.

<details>
<summary>Original summary in English</summary>

## Summary by Sourcery

Make obsolete Battery Sessions device cleanup compatible with both current and older supported Home Assistant Core versions.

Bug Fixes:
- Prevent setup failures on older supported Home Assistant Core versions by falling back to the legacy device registry lookup when the config-entry-scoped lookup is unavailable.
- Continue removing obsolete Battery Sessions umbrella devices across supported Home Assistant Core versions.

Tests:
- Add regression coverage for both the preferred and legacy device registry lookup paths using Home Assistant’s real device registry.

</details>

</details>

</details>

</details>

</details>

</details>

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved compatibility with different Home Assistant Core versions during setup.
  - Automatically removes obsolete Battery Sessions devices without causing setup failures.

### CODE REVIEW

**Review by HiDiHo01 — APPROVED** [review]
Why did they remove it when it should be removed in 2027.9 ?

Or redirected the old function to the new identityer till everybody made the transition.
