### ISSUE TITLE
AttributeError: 'DeviceRegistry' object has no attribute 'async_get_device_by_identifier' — crashes setup in v2026.9.9r2

### ISSUE THREAD

**Issue by Qilius** [HiDiHo01/home-assistant-frank_energie#307]
## Description

After updating to v2026.9.9r2 (via HACS) and restarting Home Assistant, the `frank_energie` config entry fails to set up entirely with an `AttributeError`. No entities are created — the integration is completely broken until reverted or patched.

## Steps to reproduce

1. Have frank_energie installed via HACS on a previous working version (v2026.8.8 in my case)
2. Update to v2026.9.9r2 via HACS
3. Restart Home Assistant
4. Check the log

## Expected behavior

The integration sets up normally and price/battery/charger entities are created.

## Actual behavior

ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <name> for frank_energie
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frank_energie/init.py", line 94, in async_setup_entry
    return await component.setup()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frank_energie/init.py", line 231, in setup
    if device := device_registry.async_get_device_by_identifier(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DeviceRegistry' object has no attribute 'async_get_device_by_identifier'

## Root cause

In `custom_components/frank_energie/__init__.py`, `setup()` runs this cleanup block for a legacy "Battery Sessions" umbrella device before creating the API/coordinators:

```python
device_registry = dr.async_get(self.hass)
if device := device_registry.async_get_device_by_identifier(
    (DOMAIN, f"{self.entry.entry_id}_{SERVICE_NAME_BATTERY_SESSIONS}"),
    config_entry_id=self.entry.entry_id,
):
    device_registry.async_remove_device(device.id)
    _LOGGER.debug("Removed obsolete Battery Sessions umbrella device")

async_get_device_by_identifier is not a method on Home Assistant Core's DeviceRegistry class — this looks like it was introduced in the same refactor that closed #279 (device_registry.async_get_device is deprecated), possibly mixing up the module-level helper with the instance method, or a method name that never existed in Core. This appears to still be present on main as of 2026-09-14.

Suggested fix

Replace the call with the actual Core API, e.g.:

device_registry = dr.async_get(self.hass)
if device := device_registry.async_get_device(
    identifiers={(DOMAIN, f"{self.entry.entry_id}_{SERVICE_NAME_BATTERY_SESSIONS}")}
):
    device_registry.async_remove_device(device.id)
    _LOGGER.debug("Removed obsolete Battery Sessions umbrella device")

(Please double check the exact signature against the HA Core version you're targeting — async_get_device takes identifiers/connections as sets of tuples, no config_entry_id kwarg.)

Workaround

As a local workaround, I removed the entire cleanup block (comment + code) from __init__.py. Since device isn't referenced anywhere else in setup(), this is safe short-term but obviously needs a proper upstream fix, since any HACS update overwrites the local patch.

Environment

- frank_energie version: v2026.9.9r2
- Home Assistant Core: 2026.7.2
- Frontend: 20260624.5
- Installation method: Home Assistant Container
